[package]
name = "snmp-parser"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]

[dependencies]
nom = {version = "^3.0", features = ["verbose-errors"]}
log = "0.3"
env_logger = "0.4"
enum_primitive = "^0.1"
rusticata-macros = "^0"
der-parser = "0.4.1"

# [dependencies.der-parser]
# path = "../der-parser"

